Adapt scripts for consul

diff --git a/bin/backup b/bin/backup
--- a/bin/backup
+++ b/bin/backup
@@ -9,7 +9,17 @@ fi
 docker exec db bash -c 'mysqldump shelf2_production --password=$DB_PASSWORD' > /tmp/shelf2.sql 2> /dev/null
 
 if [ ! -s /tmp/shelf2.sql ] ; then
-    echo 'Backup could not be created'
-    rm /tmp/shelf2.sql
+    echo 'Backup database could not be created'
+    exit 1
+fi
+
+if [ -f /tmp/consul.json ] ; then
+    rm /tmp/consul.json
+fi
+
+docker exec consul consul kv export > /tmp/consul.json
+
+if [ ! -s /tmp/consul.json ] ; then
+    echo 'Backup settings could not be created'
     exit 1
 fi
diff --git a/bin/restore b/bin/restore
--- a/bin/restore
+++ b/bin/restore
@@ -4,8 +4,9 @@
 
 echo '****** RESTORE ******'
 db=/tmp/restore/shelf2.sql
+consul=/tmp/restore/consul.json
 
-docker exec -t shelf2 rake db:create || { echo 'ERROR: Database could not be created' ; exit 1; }
+docker exec -t shelf2 envconsul -consul-addr consul:8500 -prefix shelf2-backend -upcase rake db:create || { echo 'ERROR: Database could not be created' ; exit 1; }
 
 if [ ! -f ${db} ] ; then
     echo "Db backup is not there"
@@ -18,3 +19,10 @@ if ! docker exec -t shelf2 rake status ; then
 else
     echo 'Database does not need to be restored'
 fi
+
+if [ ! -f ${consul} ] ; then
+    echo "Consul backup is not there"
+    exit 1
+fi
+
+docker exec -i consul consul kv import "$(cat ${consul})"
