Better logging

diff --git a/bin/restore b/bin/restore
--- a/bin/restore
+++ b/bin/restore
@@ -1,13 +1,15 @@
 # -*- mode: Shell-script-*-
 
 #!/usr/bin/env bash
+
+echo '****** RESTORE ******'
 cd ~
 
-docker exec -it shelf2 rake db:create || { echo 'Database could not be created' ; exit 1; }
+docker exec -it shelf2 rake db:create || { echo 'ERROR: Database could not be created' ; exit 1; }
 
 if docker exec -it shelf2 rake status ; then
     echo 'Restoring Database'
-    cat /tmp/restore/shelf2.sql | docker exec -i db bash -c 'mysql --password=$DB_PASSWORD shelf2_production' 2> /dev/null || { echo 'Database could not be restored' ; exit 1; }
+    cat /tmp/restore/shelf2.sql | docker exec -i db bash -c 'mysql --password=$DB_PASSWORD shelf2_production' 2> /dev/null || { echo 'ERROR: Database could not be restored' ; exit 1; }
 else
     echo 'Database does not need to be restored'
 fi
diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -1,6 +1,7 @@
 # -*- mode: Shell-script-*-
 #!/usr/bin/env bash
 
+echo '****** UPDATE ******'
 cd ~
 
 if [ ! -d erza ] ; then
@@ -11,13 +12,13 @@ fi
 cd erza
 
 echo '*** Pulling latest changes from main repository ***'
-git pull origin master || { echo 'Could not pull from origin' ; exit 1; }
+git pull origin master || { echo 'ERROR: Could not pull from origin' ; exit 1; }
 echo '*** Pulling latest changes from submodules ***'
-git submodule update --recursive || { echo 'Could not update submodules' ; exit 1; }
+git submodule update --recursive || { echo 'ERROR: Could not update submodules' ; exit 1; }
 
 echo '*** Pulling latest images ***'
-docker-compose pull || { echo 'Could not pull images'; exit 1; }
+docker-compose pull || { echo 'ERROR: Could not pull images'; exit 1; }
 echo '*** Building images ***'
-docker-compose build || { echo 'Could not build images'; exit 1; }
+docker-compose build || { echo 'ERROR: Could not build images'; exit 1; }
 echo '*** Starting images ***'
-docker-compose up -d || { echo 'Could not start images'; exit 1; }
+docker-compose up -d || { echo 'ERROR: Could not start images'; exit 1; }
