More comprehensive restore that accounts for existing db

diff --git a/bin/restore b/bin/restore
--- a/bin/restore
+++ b/bin/restore
@@ -3,4 +3,11 @@
 #!/usr/bin/env bash
 cd ~
 
-cat /tmp/restore/shelf2.sql | docker exec -i db bash -c 'mysql --password=$DB_PASSWORD shelf2_production' 2> /dev/null
+docker exec -it shelf2 rake db:create || { echo 'Database could not be created' ; exit 1; }
+
+if docker exec -it shelf2 rake status ; then
+    echo 'Restoring Database'
+    cat /tmp/restore/shelf2.sql | docker exec -i db bash -c 'mysql --password=$DB_PASSWORD shelf2_production' 2> /dev/null || { echo 'Database could not be restored' ; exit 1; }
+else
+    echo 'Database does not need to be restored'
+fi
