Extends scripts for CI

diff --git a/bin/restore b/bin/restore
--- a/bin/restore
+++ b/bin/restore
@@ -3,13 +3,18 @@
 #!/usr/bin/env bash
 
 echo '****** RESTORE ******'
-cd ~
+db=/tmp/restore/shelf2.sql
 
 docker exec -t shelf2 rake db:create || { echo 'ERROR: Database could not be created' ; exit 1; }
 
+if [ ! -f ${db} ] ; then
+    echo "Db backup is not there"
+    exit 1
+fi
+
 if ! docker exec -t shelf2 rake status ; then
     echo 'Restoring Database'
-    cat /tmp/restore/shelf2.sql | docker exec -i db bash -c 'mysql --password=$DB_PASSWORD shelf2_production' 2> /dev/null || { echo 'ERROR: Database could not be restored' ; exit 1; }
+    cat $db | docker exec -i db bash -c 'mysql --password=$DB_PASSWORD shelf2_production' 2> /dev/null || { echo 'ERROR: Database could not be restored' ; exit 1; }
 else
     echo 'Database does not need to be restored'
 fi
diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -2,23 +2,23 @@
 #!/usr/bin/env bash
 
 echo '****** UPDATE ******'
-cd ~
+repo=/srv/erza
 
-if [ ! -d erza ] ; then
+if [ ! -d ${repo} ] ; then
     echo 'configuration is not there'
     exit 1
 fi
 
-cd erza
+cd ${repo}
 
 echo '*** Pulling latest changes from main repository ***'
 git pull origin master || { echo 'ERROR: Could not pull from origin' ; exit 1; }
 echo '*** Pulling latest changes from submodules ***'
 repos=$(git submodule | awk '{ print $2 }')
-for repo in $repos ; do
-    echo "*** Pulling changes from ${repo} ***"
-    pushd $repo
-    git pull origin master || { echo "Error: Could not pull ${repo}" ; exit 1; }
+for subm in $repos ; do
+    echo "*** Pulling changes from ${subm} ***"
+    pushd $subm
+    git pull origin master || { echo "Error: Could not pull ${subm}" ; exit 1; }
     popd
 done
 
