take images down before starting them up

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -21,4 +21,5 @@ docker-compose pull || { echo 'ERROR: Could not pull images'; exit 1; }
 echo '*** Building images ***'
 docker-compose build || { echo 'ERROR: Could not build images'; exit 1; }
 echo '*** Starting images ***'
+docker-compose down || { echo 'ERROR: Could not stop images' ; exit 1; }
 docker-compose up -d || { echo 'ERROR: Could not start images'; exit 1; }
